[tool.poetry]
name = "homemade-motion-capture"
version = "0.1.0"
description = ""
authors = ["kristina-aino <kristina.ai@proton.me>"]
readme = "README.md"
packages = [{include = "homemade_motion_capture"}]

[tool.poetry.dependencies]
python = "^3.10"
notebook = "^7.2.0"
numpy = "^1.26.4"
pillow = "^10.3.0"
matplotlib = "^3.9.0"
quaternions-for-python = "^1.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
