backbone: "convnextv2_atto.fcmae_ft_in1k"

heads:
  personBbox:
    input_dim: 320
    input_sequence_length: 49
    output_dim: 4
    output_sequence_length: 10
    depth: 1
    continuous_output: True
  headBbox:
    input_dim: 320
    input_sequence_length: 49
    output_dim: 4
    output_sequence_length: 10
    depth: 1
    continuous_output: True