heads:
  bbox:
    output_size: 4
    output_length: ${experiment.numFaces}
    loss_fn: "l1_loss"
    latent_size: ${experiment.headLatentSize}
    depth_multiple: ${experiment.headDepthMultiple}
  bbox-validity:
    output_size: 2
    output_length: ${experiment.numFaces}
    loss_fn: "cross_entropy"
    latent_size: ${experiment.headLatentSize}
