checkpoint_callback:
  dirpath: "checkpoints/${experiment.experimentName}/${experiment.runName}"
  save_top_k: 1
  every_n_epochs: 1
  monitor: "val_loss"
  filename: "{epoch}-{step}-{val_loss:.4f}"
  mode: "min"
  verbose: true
logger:
  experiment_name: ${experiment.experimentName}
  run_name: ${experiment.runName}
  save_dir: "logs/"
  tracking_uri: ~
