defaults:
  - defaults

trainer:
  accelerator: "cuda"
  devices:
    - 0
  max_epochs: 100

# model_training:
#   train_backbone: false
#   optimizer_kwargs: 
#     lr: 4e-3
#     weight_decay: 6e-4
#   lr_scheduler_warmup_epochs: 5
#   lr_scheduler_kwargs:
#     T_0: 25 # Number of iterations for the first restart.
#     T_mult: 1 # A factor increases T_{i} after a restart. Default: 1.
#     eta_min: 1e-5 # Minimum learning rate. Default: 0.

datamodule:
  image_augmentation: "INPLACE"
  batch_size: 64
  train_val_split: [0.8, 0.2]
  num_workers: 2