defaults:
  - defaults

trainer:
  accelerator: "cuda"
  devices:
    - 0
  max_epochs: 100
  accumulate_grad_batches: 5
  gradient_clip_algorithm: "norm"
  gradient_clip_val: 1

model_training:
  optimizer: "AdamW"
  optimizer_kwargs: 
    lr: 4e-3
    weight_decay: 6e-4
  lr_scheduler_warmup_epochs: 5
  lr_scheduler: "CosineAnnealingWarmRestarts"
  lr_scheduler_kwargs:
    T_0: 50 # Number of iterations for the first restart.
    T_mult: 1 # A factor increases T_{i} after a restart. Default: 1.
    eta_min: 1e-5 # Minimum learning rate. Default: 0.
  
  reconstruction_loss_scale: 1.0
  codebook_loss_scale: 0.2
  prediction_loss_scales: ~

data_module:
  image_augmentation: "INPLACE"
  batch_size: 40
  train_val_test_split: [0.8, 0.15, 0.05]
  num_train_workers: 2
  num_val_workers: 2