
loss_fn: "l1_loss"
optimizer: "AdamW"
optimizer_kwargs: 
  lr: [1e-4, 1e-02]
  weight_decay: [0.0005, 0.05]
lr_scheduler: "CosineAnnealingLR"
lr_scheduler_kwargs:
  T_max: [5, 20]
  eta_min: [1e-06, 1e-04]
  last_epoch: -1